replicaCount: 1

image:
  repository: bkimminich/juice-shop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""
  rewriteTarget: "/"
  path: "/"
  pathType: Prefix
