replicaCount: 1

image:
  repository: bkimminich/juice-shop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: "aa8a9771096a934295bd8295b30b8dd52-1392346801.eu-west-1.elb.amazonaws.com"
  rewriteTarget: "/"
  path: "/"
  pathType: Prefix
