name: Deploy juice-shop Helm Chart
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Deploy Helm chart
          run: |
            aws eks update-kubeconfig --name k8s-task-cluster --region eu-west-1 
            helm upgrade --install juice-shop . --namespace juice-shop --create-namespace
